version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: jupyter notebook --port 8888 --ip=0.0.0.0 --allow-root
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./jupyter:/jupyter
    working_dir: /jupyter
    tty: true